number=int(input("Input 4-digit number: "))
print("Product of digits: ", (number//1000%10)*(number//100%10)*(number//10%10)*(number%10))
print("Reversible number: ", str(''.join(reversed(str(number)))))
ll=list(str(number))
ll.sort()
print("Sorted number: ", ''.join(ll))